### ISSUE TITLE
opnsynid_receivable_aging_aeroo_report

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/opnsynid-accounting-report#49]
**Acceptance Criteria**:
1. Wizard mengikuti screenshot berikut:
   ![selection_1](https://cloud.githubusercontent.com/assets/1947376/12012622/2bac1404-ad30-11e5-9002-d5d5b67ee2ef.png)
   ditambahkan **Date Start** dan **Date End** di atas Date as of (tidak required)
2. Template mengikuti format berikut:
   [contoh_template.zip](https://github.com/open-synergy/opnsynid-accounting-report/files/72855/contoh_template.zip)
3. Journal hanya menampilkan **sale** journal dan harus dimiliki oleh **company**
4. Jika journal dipilih, maka hanya tampilkan receivable account move dengan journal yang dipilih. Jika journal tidak dipilih, maka tampilkan semua receivable account move milik **company** yang dipilih
5. Tampilkan receivable account move dengan tanggal yang sesuai dengan kriteria **start date/end date**.
6. Hanya tampilkan receivable account move yang masih mempunyai residual pada waktu **date as of**
7. Internal antar periode aging dapat diubah sesuai dengan isian **period lenght** 
8. Menggunakan API 8.0
9. Output hanya ods dan xls
10. Menu diletakan di bawah Accounting -> Reporting
11. Hanya tampilkan **fiscal year** milik **company** yang dipilih

**Comment by mikevhe18** [comment]
@andhit-r Mas, untuk contoh templatenya isinya kosong mas. Yang keliatan cuman headernya saja

**Comment by mikevhe18** [comment]
PR to OpenSynergy #55
